### ISSUE TITLE
Readme Need to be Updated

### ISSUE THREAD

**Issue by deepak2431** [taapas1128/Calculator_pyqt#12] opened 2018-12-06 16:05 UTC
Contribution Guidelines need to be added and proper way to run the file should be added.If possible the images of the UI design also need to be added.

**Comment by deepak2431** [comment] 2018-12-06 16:07
If you would accept this issue I would like to work on this.

**Comment by taapas1128** [comment] 2018-12-06 16:54
this is dupe of #9 . Work there.

**Closed** 2018-12-06 16:56 UTC
